global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: Amazon-Cloud
    static_configs:
      - targets:
          - 44.208.214.0:9100
  - job_name: Amazon-Test
    static_configs:
      - targets:
          - 44.208.214.5:9100