global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090

- job_name: Amazon-Cloud
    static_configs:
    - targets:
       - 52.71.101.165:9100