name: manual performing Individual task

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        type: choice
        options:
          - 'upgrade-package'
          - 'deploy-prometheus'
          - 'Delete-default-container'
          - 'delete-all-local-temp-files'

jobs:
  upgrade-package:
    if: github.event.inputs.environment == 'upgrade-package'
    runs-on: self-hosted
    steps:
      - name: Upgrade Package
        working-directory: scripts
        run: |
            echo "Upgrading All scanning tools"
            whoami
            chmod +x upgrade-install.sh
            sudo ./upgrade-install.sh
  compose-up-task:
    if: github.event.inputs.environment == 'deploy-prometheus'
    runs-on: self-hosted
    steps:
      - name: Scanning sub-domains
        working-directory: scripts 
        run: |
          chmod +x prometheus-setup.sh
          ./prometheus-setup.sh

  compose-down-task:
    if: github.event.inputs.environment == 'Delete-default-container'
    runs-on: self-hosted
    steps:
        - name: Making Docker-compose down
          run: |
              cd $HOME/prometheus/
              docker compose down  

  Delete-tmp-file:
    if: github.event.inputs.environment == 'delete-all-local-temp-files'
    runs-on: self-hosted
    steps:
        - name: Authenticating mega and copying file
          run: |
              ls -al